<?php

namespace AppBundle\Repository\Products;

/**
 * BlouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlouseRepository extends \Doctrine\ORM\EntityRepository
{
}
