<?php

namespace AppBundle\Repository\Products;

/**
 * JacketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JacketRepository extends \Doctrine\ORM\EntityRepository
{
}
