<?php

namespace AppBundle\Repository\Products;

/**
 * SweaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SweaterRepository extends \Doctrine\ORM\EntityRepository
{
}
