<?php

namespace AppBundle\Repository\Products;

/**
 * TrousersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrousersRepository extends \Doctrine\ORM\EntityRepository
{
}
