<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * Finds products by gender and category
     *
     * @param string $gender
     * @param string $category
     * @param int $limit
     * @param int $offset
     * @return array The objects
     */
    public function findProductsByGenderAndCategory($gender, $category, $limit = null, $offset = null)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "SELECT p FROM AppBundle\Entity\Product p JOIN p.category c WHERE p.gender = :gend AND c.name = :cat");
        $query->setParameter('gend', $gender);
        $query->setParameter('cat', $category);
        if($limit) $query->setMaxResults($limit);
        if($offset) $query->setFirstResult($offset);
        return $query->getResult();
    }

    public function countProductsByGenderAndCategory($gender, $category)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            "SELECT COUNT(p.id) FROM AppBundle\Entity\Product p
             JOIN p.category c WHERE p.gender = :gend AND c.name = :cat");
        $query->setParameter('gend', $gender);
        $query->setParameter('cat', $category);
        return $query->getSingleScalarResult();
    }
}
