# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


    cart_manager:
        class: AppBundle\Utils\CartManager
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']

    currency_manager:
            class: AppBundle\Utils\CurrencyManager
            arguments: ['@doctrine.orm.entity_manager', '@request_stack']

    app.product_paginator:
        class: AppBundle\Utils\Paginator
        arguments: ['@product_manager', '@doctrine.orm.entity_manager', '@request_stack', '@router']

    my_event.listener:
        class: AppBundle\EventListener\MyEventListener
        tags:
        - {name: kernel.event_listener, event: my_event, method: onMyEvent}

    app.crumbs_generator:
        class: AppBundle\Utils\CrumbsGenerator\CrumbsGenerator
        arguments: ['@router', '@doctrine.orm.entity_manager']

    product_manager:
        class: AppBundle\Utils\ProductManager
        arguments: ['@request_stack', '@doctrine.orm.entity_manager', '@currency_manager', '@filters_handler']

    filters_handler:
        class: AppBundle\Utils\Filters\FiltersHandler
        arguments: ['@request_stack', '@doctrine.orm.entity_manager', '@router', '@form.factory', '@currency_manager']
