# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    cartManager:
        class: AppBundle\Utils\CartManager
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']

    app.product_paginator:
        class: AppBundle\Utils\Paginator
        arguments: ['@doctrine.orm.entity_manager']

    my_event.listener:
        class: AppBundle\EventListener\MyEventListener
        tags:
        - {name: kernel.event_listener, event: my_event, method: onMyEvent}

    app.crumbs_generator:
        class: AppBundle\Utils\CrumbsGenerator\CrumbsGenerator
        arguments: ['@router']
